name: Release

on:
  push:
    tags:
      - 'v*' # v1.0, v20.15.10 などのタグがプッシュされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PPTGenVoice2.ppam
          generate_release_notes: true
